### ISSUE TITLE
Include Gameplay screenshots for each level

### ISSUE THREAD

**Issue by Dcruise546** [nishanthgreen/Scolaro-Ventures#10]
Please attach the screenshots only after merging my pull request from the branch 'Dcruise546-readme-patch'.

At least, one screenshot will be sufficient for each level.

**Comment by Dcruise546** [comment]
The screenshot has to be added on ReadMe.md. Please consider the following project as a reference [https://github.com/ai/size-limit#readme](url)

**Comment by laki2603** [comment]
Added the screenshots  in readme
